config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'top#main'
  get 'top/main'
  resources :products
  resources :cart_items, only: [:create, :destroy]
  resources :carts, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
    has_many :cart_items, dependent: :destroy
     def add_product(product_id)
        current_item = cart_items.find_by(product_id)
        if current_item
            current_item.qty += 1
        else
            current_item = cart_items.build(product_id: product_id)
        end
        current_item
     end
     
     
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :product
  belongs_to :cart
  
end

app/models/product.rb
class Product < ApplicationRecord
    has_many :cart_items
   
    validates :name, :price, presence: true
    validates :price, numericality: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    private
      def current_cart
          if session[:cart_id]
              cart = Cart.find(session[:cart_id])
          else
              cart = Cart.create
              session[:cart_id] = cart.id
          end
          cart
      end
      helper_method :current_cart
end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController
    def create
        @cart = current_cart
        @product = Product.find(params[:product_id])
        @cart_item = @cart.add_product(@product_id)
      
        
        @cart_item.save
       
        redirect_to  current_cart   
        

    end
    def destroy
        @cart_item = CartItem.find(params[:id])
        @cart_item.destroy
        redirect_to current_cart
    end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
    def show
        @cart = current_cart
        @cart_items = current_cart.cart_items
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
    def index
        @products = Product.all
    end
    
    def new
        @product = Product.new
    end
    
    def create
        @product = Product.new(name: params[:product][:name], price: params[:product][:price])
        if @product.save
            
            flash[:success] = "登録完了"
            redirect_to products_path
        else
            flash[:failed] = "登録失敗"
            render 'new'
        end
    end
    
    def destroy
        product = Product.find(params[:id])
        product.destroy
           
        redirect_to products_path, flash: {destroy:  "ツイートを削除しました。"}
    end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
    def main
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/carts/show.html.erb
<h2>カート</h2>
<table>
	<tr>
		<th>商品名</th>
		<th>価格</th>
		<th>数量</th>
	
	</tr>
	<% @cart.cart_items.each do |item| %>
	<tr>
		<td text-align:center;><font size="4"><%= item.product.name %></font></td>
		<td text-align:center;><font size="4"><%= (item.product.price).to_i %>円</font></td>
        <td text-align:center;><font size="4"><%= item.qty %></font></td>
       
        <td><%= link_to '削除', item, method: :delete %></td>
	</tr>
		
	<% end %>
	
</table>


<%= link_to '戻る', root_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>S</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/products/index.html.erb
<h2>商品一覧</h2>
<table>
	<% @products.each do |good| %>
	<tr>
		<td>
			<p><font size="5">商品名：<%= good.name %></font></p>
			<p><font size="4">価格：<%= good.price %>円</font></p>
		</td>
		<td>
			<%= button_to 'カートに入れる', cart_items_path(product_id: good), class: 'fbtn' %>
			<%= link_to '削除', good, method: :delete %>
		</td>
	</tr>

	<% end %>
</table>


<%= link_to "商品登録", new_product_path %>
<%= link_to "戻る", root_path %>

app/views/products/new.html.erb
<h2>新商品登録</h2>
<%= form_for @product do |form| %>
 <%= form.label :name, "商品名" %>
 <%= form.text_field :name %>
 <%= form.label :price, "価格" %>
 <%= form.text_field :price %>
 <%= form.submit "登録" %>
<% end %>

<%= link_to '戻る', root_path %>

app/views/top/main.html.erb
<h2>shopping cart</h2>
<%= link_to 'カート', cart_path(current_cart) %>
<%= link_to '商品登録', new_product_path %>
<%= link_to '商品一覧', products_path %>